---
- name: Actual**ar Linux
  hosts: all
  become: t**e
  serial: 5

  tasks:

    - na**: Actualizar cache APT
      apt:**       update_cache: yes

    - n**e: Actualizar paquetes
      apt:**       upgrade: dist
        auto**move: true
        autoclean: tru**
    - name: Verificar reinicio p**diente
      stat:
        path: **ar/run/reboot-required
      regi**er: reboot_required

    - name: **strar resultado
      debug:
    **  msg:
          - "Host: {{ inve**ory_hostname }}"
          - "Reb**t requerido: {{ reboot_required.s**t.exists | ternary('SI','NO') }}"**
