---
- hosts: all
  gather_facts: false

  tasks:

    - name: Ver usuario
      raw: whoami
      register: usuario

    - debug:
        var: usuario.stdout

    - name: Ver Python
      raw: python3 --version || python --version
      register: py

    - debug:
        var: py.stdout

    - name: Ver PATH
      raw: echo $PATH
      register: path

    - debug:
        var: path.stdout
