---
- hosts: all
  gather_facts: false

  tasks:

    - name: Usuario
      raw: whoami
      register: usuario

    - debug:
        var: usuario.stdout

    - name: Python
      raw: /usr/bin/python3 --version
      register: py

    - debug:
        var: py.stdout
